# Generated by Django 3.1.4 on 2021-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_all_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_store',
            name='products',
            field=models.ManyToManyField(blank=True, to='stockmgmt.Stock'),
        ),
    ]
