# Generated by Django 3.1.3 on 2021-01-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_all_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_store',
            name='products',
        ),
        migrations.AddField(
            model_name='stock',
            name='issue_by_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_to_model', to='stockmgmt.all_store'),
        ),
        migrations.AddField(
            model_name='stock',
            name='issue_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_by_model', to='stockmgmt.all_store'),
        ),
    ]
