# Generated by Django 3.1.3 on 2021-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0009_transit_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_items',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
