# Generated by Django 3.1.3 on 2021-01-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0010_sold_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ordered_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
