# Generated by Django 3.1.3 on 2021-01-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_auto_20210112_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.subcategory', verbose_name='UNIT'),
        ),
    ]
