# Generated by Django 3.1.3 on 2021-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0016_individual_sold_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_sold_item',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
