# Generated by Django 3.1.3 on 2021-01-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_individual_sold_item_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_sales_total', models.FloatField()),
                ('daily_quantity_total', models.IntegerField()),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.all_store')),
            ],
        ),
    ]
