# Generated by Django 3.1.3 on 2021-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0018_date_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ordered_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='reorder'),
        ),
    ]
